python main.py configs/thesis_organized/1.2/uqc_1qubit_XY.py
python main.py configs/thesis_organized/1.2/uqc_1qubit_XY.py
python main.py configs/thesis_organized/1.2/uqc_1qubit_XY.py
python main.py configs/thesis_organized/1.2/uqc_1qubit_ZX.py
python main.py configs/thesis_organized/1.2/uqc_1qubit_ZX.py
python main.py configs/thesis_organized/1.2/uqc_1qubit_ZX.py
python main.py configs/thesis_organized/1.2/uqc_1qubit_ZY.py
python main.py configs/thesis_organized/1.2/uqc_1qubit_ZY.py
python main.py configs/thesis_organized/1.2/uqc_1qubit_ZY.py