python main.py configs/thesis_organized/1.1/skolik_datareup.py
python main.py configs/thesis_organized/1.1/skolik_baseline.py
python main.py configs/thesis_organized/1.1/skolik_datareup_no_in.py
python main.py configs/thesis_organized/1.1/skolik_baseline_no_in.py
python main.py configs/thesis_organized/1.1/skolik_datareup_no_out.py
python main.py configs/thesis_organized/1.1/skolik_baseline_no_out.py
python main.py configs/thesis_organized/1.1/skolik_datareup_no_in_out.py
python main.py configs/thesis_organized/1.1/skolik_baseline_no_in_out.py
python main.py configs/thesis_organized/1.1/skolik_datareup.py
python main.py configs/thesis_organized/1.1/skolik_baseline.py
python main.py configs/thesis_organized/1.1/skolik_datareup_no_in.py
python main.py configs/thesis_organized/1.1/skolik_baseline_no_in.py
python main.py configs/thesis_organized/1.1/skolik_datareup_no_out.py
python main.py configs/thesis_organized/1.1/skolik_baseline_no_out.py
python main.py configs/thesis_organized/1.1/skolik_datareup_no_in_out.py
python main.py configs/thesis_organized/1.1/skolik_baseline_no_in_out.py
python main.py configs/thesis_organized/1.1/skolik_datareup.py
python main.py configs/thesis_organized/1.1/skolik_baseline.py
python main.py configs/thesis_organized/1.1/skolik_datareup_no_in.py
python main.py configs/thesis_organized/1.1/skolik_baseline_no_in.py
python main.py configs/thesis_organized/1.1/skolik_datareup_no_out.py
python main.py configs/thesis_organized/1.1/skolik_baseline_no_out.py
python main.py configs/thesis_organized/1.1/skolik_datareup_no_in_out.py
python main.py configs/thesis_organized/1.1/skolik_baseline_no_in_out.py